### PR TITLE
Riskset_info + minor fix

### PR DESCRIPTION
**Pull request by adibender**
- @fabian-s  `riskset_info` pr
- minor example fix

### CODE REVIEW

**Comment by adibender** [comment]
Cool feature @fabian-s, but do wee need the sample info in addition to censoring/event information?

**Comment by fabian-s** [comment]
.... covariate summary might be interesting for description/exploratory purposes, i thought...?

**Comment by adibender** [comment]
true, may be interesting some times. On the other hand if there are a lot of covariates might be  tidious to carry them along just to get risk set information + we can already create that information using 
`ped %>% group_by(interval) %>% sample_info()` and than join with risk set info if necessary?

**Comment by fabian-s** [comment]
true.... i'll remove it then...

**Pull request merged**
